import { useEffect, useMemo, useState } from "react";
import PropTypes from "prop-types";

const genderOptions = [
  { value: "male", label: "Nam" },
  { value: "female", label: "Nữ" },
  { value: "unknown", label: "Không xác định" }
];

const missingTemplate = {
  case_id: "",
  name: "",
  age_at_disappearance: "",
  year_disappeared: "",
  gender: "unknown",
  location_last_seen: "",
  contact: "",
  description: ""
};

const foundTemplate = {
  found_id: "",
  name: "",
  current_age_estimate: "",
  gender: "unknown",
  current_location: "",
  finder_contact: "",
  description: ""
};

const numberFields = {
  missing: ["age_at_disappearance", "year_disappeared"],
  found: ["current_age_estimate"]
};

const templateByMode = {
  missing: missingTemplate,
  found: foundTemplate
};

const autoGeneratedFields = {
  missing: ["case_id"],
  found: ["found_id"]
};


const labels = {
  name: "Họ và tên",
  age_at_disappearance: "Tuổi khi mất tích",
  year_disappeared: "Năm mất tích",
  gender: "Giới tính",
  location_last_seen: "Địa điểm cuối cùng",
  contact: "Liên hệ gia đình",
  description: "Mô tả bổ sung",
  current_age_estimate: "Độ tuổi hiện tại (ước tính)",
  current_location: "Địa điểm hiện tại",
  finder_contact: "Liên hệ người tìm thấy"
};

const placeholders = {
  name: {
    missing: "Họ và tên",
    found: "Họ và tên (nếu biết)"
  },
  age_at_disappearance: "Tuổi khi mất tích",
  year_disappeared: "Năm mất tích",
  gender: "Giới tính",
  location_last_seen: "Địa điểm cuối cùng",
  contact: "Liên hệ gia đình",
  description: "Đặc điểm nhận dạng, trang phục, tình trạng sức khỏe...",
  current_age_estimate: "Độ tuổi hiện tại (ước tính)",
  current_location: "Địa điểm hiện tại",
  finder_contact: "Liên hệ người tìm thấy"
};

const helperText = {
  description: "Thông tin giúp tăng độ chính xác nhận diện.",
  name: "Tùy chọn - Nhập tên nếu biết"
};

export default function UploadForm({ mode, onSubmit, loading }) {
  const [metadata, setMetadata] = useState(() => ({ ...templateByMode[mode] }));
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState("");

  // Handle image preview - create object URL when image file changes
  useEffect(() => {
    if (!imageFile) {
      setImagePreview("");
      return undefined;
    }

    const objectUrl = URL.createObjectURL(imageFile);
    setImagePreview(objectUrl);

    return () => {
      URL.revokeObjectURL(objectUrl);
    };
  }, [imageFile]);

  const fields = useMemo(() => Object.keys(templateByMode[mode]), [mode]);
  const inputFields = useMemo(
    () => fields.filter((field) => !autoGeneratedFields[mode].includes(field)),
    [fields, mode]
  );

  const handleInputChange = (event) => {
    const { name, value } = event.target;
    setMetadata((prev) => ({
      ...prev,
      [name]: value
    }));
  };

  const handleFileChange = (event) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith("image/")) {
      alert("Vui lòng chọn đúng định dạng ảnh.");
      return;
    }

    setImageFile(file);
  };

  const normalizeMetadata = () => {
    const normalized = { ...metadata };
    autoGeneratedFields[mode].forEach((field) => {
      delete normalized[field];
    });
    numberFields[mode].forEach((field) => {
      if (normalized[field]) {
        normalized[field] = Number(normalized[field]);
      }
    });
    // Remove empty optional fields for found mode
    if (mode === "found") {
      if (!normalized.name || normalized.name.trim() === "") {
        delete normalized.name;
      } else {
        normalized.name = normalized.name.trim();
      }
    }
    return normalized;
  };

  const validateForm = () => {
    const errors = [];
    const normalized = normalizeMetadata();

    if (mode === "missing") {
      if (!normalized.name || normalized.name.trim().length < 2) {
        errors.push("• Họ và tên phải có ít nhất 2 ký tự");
      }
      if (!normalized.age_at_disappearance || normalized.age_at_disappearance < 0 || normalized.age_at_disappearance > 120) {
        errors.push("• Tuổi khi mất tích phải là số từ 0 đến 120");
      }
      if (!normalized.year_disappeared || normalized.year_disappeared < 1900 || normalized.year_disappeared > new Date().getFullYear()) {
        errors.push(`• Năm mất tích phải từ 1900 đến ${new Date().getFullYear()}`);
      }
      if (!normalized.location_last_seen || normalized.location_last_seen.trim().length < 3) {
        errors.push("• Địa điểm cuối cùng phải có ít nhất 3 ký tự");
      }
      if (!normalized.contact || normalized.contact.trim().length === 0) {
        errors.push("• Vui lòng nhập thông tin liên hệ");
      }
    } else {
      if (!normalized.current_age_estimate || normalized.current_age_estimate < 0 || normalized.current_age_estimate > 120) {
        errors.push("• Độ tuổi hiện tại phải là số từ 0 đến 120");
      }
      if (!normalized.current_location || normalized.current_location.trim().length < 3) {
        errors.push("• Địa điểm hiện tại phải có ít nhất 3 ký tự");
      }
      if (!normalized.finder_contact || normalized.finder_contact.trim().length === 0) {
        errors.push("• Vui lòng nhập thông tin liên hệ người tìm thấy");
      }
    }

    return errors;
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    
    if (!imageFile) {
      alert("Vui lòng chọn ảnh trước khi gửi.");
      return;
    }

    const validationErrors = validateForm();
    if (validationErrors.length > 0) {
      // Pass validation errors to parent via onSubmit with error flag
      onSubmit({
        error: true,
        message: `Vui lòng kiểm tra lại:\n${validationErrors.join("\n")}`
      });
      return;
    }

    const payload = {
      imageFile,
      metadata: normalizeMetadata()
    };

    onSubmit(payload);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2">
        {inputFields.map((field) => (
          <div key={field} className={field === "description" ? "md:col-span-2" : ""}>
            <label className="block text-sm font-semibold text-slate-600">
              {labels[field]}
            </label>
            {field === "gender" ? (
              <select
                name={field}
                value={metadata[field]}
                onChange={handleInputChange}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-slate-700 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-100"
              >
                {genderOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            ) : field === "description" ? (
              <textarea
                name={field}
                rows={3}
                value={metadata[field]}
                onChange={handleInputChange}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-slate-700 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-100"
                placeholder="Đặc điểm nhận dạng, trang phục, tình trạng sức khỏe..."
              />
            ) : (
              <input
                type={numberFields[mode].includes(field) ? "number" : "text"}
                name={field}
                value={metadata[field]}
                onChange={handleInputChange}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-slate-700 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-100"
                placeholder={
                  typeof placeholders[field] === "object"
                    ? placeholders[field][mode]
                    : placeholders[field] || labels[field]
                }
              />
            )}
            {helperText[field] && (
              <p className="mt-1 text-xs text-slate-400">{helperText[field]}</p>
            )}
          </div>
        ))}
      </div>

      <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50/60 p-4">
        <label className="flex cursor-pointer flex-col items-center justify-center gap-2 rounded-xl p-6 text-center hover:bg-white">
          <span className="text-base font-semibold text-slate-700">
            Tải ảnh {mode === "missing" ? "người mất tích" : "vừa tìm thấy"}
          </span>
          <span className="text-sm text-slate-500">
            Hỗ trợ JPG, PNG. Kích thước &lt; 10MB.
          </span>
          <input
            type="file"
            accept="image/*"
            className="hidden"
            onChange={handleFileChange}
          />
          {imagePreview && (
            <img
              src={imagePreview}
              alt="Preview"
              className="mt-4 h-48 w-full rounded-2xl object-cover shadow-inner"
            />
          )}
        </label>
      </div>

      <button
        type="submit"
        disabled={loading}
        className="w-full rounded-2xl bg-gradient-to-r from-primary-600 to-blue-600 px-6 py-3 text-base font-semibold text-white shadow-lg shadow-primary-500/30 transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-70"
      >
        {loading ? "Đang xử lý..." : "Phân tích & tìm kiếm"}
      </button>
    </form>
  );
}

UploadForm.propTypes = {
  mode: PropTypes.oneOf(["missing", "found"]).isRequired,
  onSubmit: PropTypes.func.isRequired,
  loading: PropTypes.bool
};

