import { useEffect, useMemo, useRef, useState } from "react";
import PropTypes from "prop-types";
import ConfirmationModal from "./ConfirmationModal";

const genderOptions = [
  { value: "male", label: "Nam" },
  { value: "female", label: "Nữ" }
];

const missingTemplate = {
  case_id: "",
  name: "",
  age_at_disappearance: "",
  year_disappeared: "",
  gender: "male",
  location_last_seen: "",
  contact: "",
  description: ""
};

const foundTemplate = {
  found_id: "",
  name: "",
  current_age_estimate: "",
  gender: "male",
  current_location: "",
  finder_contact: "",
  description: ""
};

const numberFields = {
  missing: ["age_at_disappearance", "year_disappeared"],
  found: ["current_age_estimate"]
};

const templateByMode = {
  missing: missingTemplate,
  found: foundTemplate
};

const autoGeneratedFields = {
  missing: ["case_id"],
  found: ["found_id"]
};


const labels = {
  name: "Họ và tên",
  age_at_disappearance: "Tuổi khi mất tích",
  year_disappeared: "Năm mất tích",
  gender: "Giới tính",
  location_last_seen: "Địa điểm cuối cùng",
  contact: "Liên hệ gia đình",
  description: "Mô tả bổ sung",
  current_age_estimate: "Độ tuổi hiện tại (ước tính)",
  current_location: "Địa điểm hiện tại",
  finder_contact: "Liên hệ người tìm thấy"
};

const placeholders = {
  name: {
    missing: "Họ và tên",
    found: "Họ và tên (nếu biết)"
  },
  age_at_disappearance: "Tuổi khi mất tích",
  year_disappeared: "Năm mất tích",
  gender: "Giới tính",
  location_last_seen: "Địa điểm cuối cùng",
  contact: "Liên hệ gia đình",
  description: "Đặc điểm nhận dạng, trang phục, tình trạng sức khỏe...",
  current_age_estimate: "Độ tuổi hiện tại (ước tính)",
  current_location: "Địa điểm hiện tại",
  finder_contact: "Liên hệ người tìm thấy"
};

const helperText = {
  description: "Thông tin giúp tăng độ chính xác nhận diện.",
  name: "Tùy chọn - Nhập tên nếu biết"
};

export default function UploadForm({ mode, onSubmit, loading }) {
  const [metadata, setMetadata] = useState(() => ({ ...templateByMode[mode] }));
  const [imageFiles, setImageFiles] = useState([]);
  const [imagePreviews, setImagePreviews] = useState([]);
  const [imageMetadataList, setImageMetadataList] = useState([]); // Per-image metadata (photo_year)
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [pendingPayload, setPendingPayload] = useState(null);
  const fileInputRef = useRef(null);

  // Handle image previews - create object URLs when image files change
  useEffect(() => {
    const previews = imageFiles.map((file) => URL.createObjectURL(file));
    setImagePreviews(previews);

    // Initialize imageMetadataList if it's empty or doesn't match imageFiles length
    if (imageMetadataList.length !== imageFiles.length) {
      setImageMetadataList(
        imageFiles.map((_, index) => imageMetadataList[index] || { photo_year: "" })
      );
    }

    return () => {
      previews.forEach((url) => URL.revokeObjectURL(url));
    };
  }, [imageFiles]);

  const fields = useMemo(() => Object.keys(templateByMode[mode]), [mode]);
  const inputFields = useMemo(
    () => fields.filter((field) => !autoGeneratedFields[mode].includes(field)),
    [fields, mode]
  );

  const handleInputChange = (event) => {
    const { name, value } = event.target;
    setMetadata((prev) => ({
      ...prev,
      [name]: value
    }));
  };

  const handleFileChange = (event) => {
    const files = Array.from(event.target.files || []);
    if (files.length === 0) return;

    // Validate all files are images
    const invalidFiles = files.filter((file) => !file.type.startsWith("image/"));
    if (invalidFiles.length > 0) {
      alert("Vui lòng chọn đúng định dạng ảnh.");
      return;
    }

    // Limit to 10 images total
    const currentCount = imageFiles.length;
    const newCount = currentCount + files.length;
    if (newCount > 10) {
      alert(`Tối đa 10 ảnh. Bạn đã chọn ${currentCount} ảnh, chỉ có thể thêm ${10 - currentCount} ảnh nữa.`);
      const allowedFiles = files.slice(0, 10 - currentCount);
      setImageFiles([...imageFiles, ...allowedFiles]);
    } else {
      setImageFiles([...imageFiles, ...files]);
    }
  };

  const handleRemoveImage = (index) => {
    setImageFiles(imageFiles.filter((_, i) => i !== index));
    setImageMetadataList(imageMetadataList.filter((_, i) => i !== index));
  };

  const handleImageMetadataChange = (index, field, value) => {
    setImageMetadataList((prev) =>
      prev.map((item, idx) => (idx === index ? { ...item, [field]: value } : item))
    );
  };

  const normalizeMetadata = () => {
    const normalized = { ...metadata };
    autoGeneratedFields[mode].forEach((field) => {
      delete normalized[field];
    });
    numberFields[mode].forEach((field) => {
      if (normalized[field]) {
        normalized[field] = Number(normalized[field]);
      }
    });
    
    // Map 'description' to 'additional_info' (BE expects 'additional_info')
    if (normalized.description !== undefined) {
      normalized.additional_info = normalized.description;
      delete normalized.description;
    }
    
    // Remove empty optional fields for found mode
    if (mode === "found") {
      if (!normalized.name || normalized.name.trim() === "") {
        delete normalized.name;
      } else {
        normalized.name = normalized.name.trim();
      }
      // Remove empty additional_info
      if (normalized.additional_info && normalized.additional_info.trim() === "") {
        delete normalized.additional_info;
      }
    }
    
    // Remove empty additional_info for missing mode too
    if (mode === "missing" && normalized.additional_info && normalized.additional_info.trim() === "") {
      delete normalized.additional_info;
    }
    
    return normalized;
  };

  const validateForm = () => {
    const errors = [];
    const normalized = normalizeMetadata();

    if (mode === "missing") {
      if (!normalized.name || normalized.name.trim().length < 2) {
        errors.push("• Họ và tên phải có ít nhất 2 ký tự");
      }
      const age = normalized.age_at_disappearance;
      if (age == null || age === '' || age < 0 || age > 120) {
        errors.push("• Tuổi khi mất tích phải là số từ 0 đến 120");
      }
      const year = normalized.year_disappeared;
      if (year == null || year === '' || year < 1900 || year > new Date().getFullYear()) {
        errors.push(`• Năm mất tích phải từ 1900 đến ${new Date().getFullYear()}`);
      }
      if (!normalized.location_last_seen || normalized.location_last_seen.trim().length < 3) {
        errors.push("• Địa điểm cuối cùng phải có ít nhất 3 ký tự");
      }
      if (!normalized.contact || normalized.contact.trim().length === 0) {
        errors.push("• Vui lòng nhập thông tin liên hệ");
      }
    } else {
      const age = normalized.current_age_estimate;
      if (age == null || age === '' || age < 0 || age > 120) {
        errors.push("• Độ tuổi hiện tại phải là số từ 0 đến 120");
      }
      if (!normalized.current_location || normalized.current_location.trim().length < 3) {
        errors.push("• Địa điểm hiện tại phải có ít nhất 3 ký tự");
      }
      if (!normalized.finder_contact || normalized.finder_contact.trim().length === 0) {
        errors.push("• Vui lòng nhập thông tin liên hệ người tìm thấy");
      }
    }

    return errors;
  };

  const handleReset = () => {
    // Reset metadata to template
    setMetadata({ ...templateByMode[mode] });
    
    // Clear image files and previews
    setImageFiles([]);
    setImagePreviews([]);
    setImageMetadataList([]);
    
    // Reset file input
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    
    if (imageFiles.length === 0) {
      alert("Vui lòng chọn ít nhất 1 ảnh trước khi gửi.");
      return;
    }

    if (imageFiles.length > 10) {
      alert("Tối đa 10 ảnh mỗi lần tải lên.");
      return;
    }

    const validationErrors = validateForm();
    if (validationErrors.length > 0) {
      // Pass validation errors to parent via onSubmit with error flag
      onSubmit({
        error: true,
        message: `Vui lòng kiểm tra lại:\n${validationErrors.join("\n")}`
      });
      return;
    }

    const payload = {
      imageFiles: imageFiles.length > 1 ? imageFiles : imageFiles, // Always use array for batch
      metadata: normalizeMetadata(),
      imageMetadataList: imageMetadataList.map((item) => ({
        ...item,
        photo_year: item.photo_year ? Number(item.photo_year) : null // Convert to number or null
      })),
      isBatch: imageFiles.length > 1 // Flag to use batch endpoint
    };

    // Show confirmation modal instead of submitting directly
    setPendingPayload(payload);
    setShowConfirmModal(true);
  };

  const handleConfirmSubmit = () => {
    setShowConfirmModal(false);
    if (pendingPayload) {
      onSubmit(pendingPayload);
      setPendingPayload(null);
    }
  };

  const handleCancelConfirm = () => {
    setShowConfirmModal(false);
    setPendingPayload(null);
  };

  return (
    <>
      <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2">
        {inputFields.map((field) => (
          <div key={field} className={field === "description" ? "md:col-span-2" : ""}>
            <label className="block text-sm font-semibold text-slate-600">
              {labels[field]}
            </label>
            {field === "gender" ? (
              <select
                name={field}
                value={metadata[field]}
                onChange={handleInputChange}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-slate-700 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-100"
              >
                {genderOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            ) : field === "description" ? (
              <textarea
                name={field}
                rows={3}
                value={metadata[field]}
                onChange={handleInputChange}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-slate-700 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-100"
                placeholder="Đặc điểm nhận dạng, trang phục, tình trạng sức khỏe..."
              />
            ) : (
              <input
                type={numberFields[mode].includes(field) ? "number" : "text"}
                name={field}
                value={metadata[field]}
                onChange={handleInputChange}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-slate-700 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-100"
                placeholder={
                  typeof placeholders[field] === "object"
                    ? placeholders[field][mode]
                    : placeholders[field] || labels[field]
                }
              />
            )}
            {helperText[field] && (
              <p className="mt-1 text-xs text-slate-400">{helperText[field]}</p>
            )}
          </div>
        ))}
      </div>

      <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50/60 p-4">
        <label className="flex cursor-pointer flex-col items-center justify-center gap-2 rounded-xl p-6 text-center hover:bg-white">
          <span className="text-base font-semibold text-slate-700">
            Tải ảnh {mode === "missing" ? "người mất tích" : "vừa tìm thấy"}
          </span>
          <span className="text-sm text-slate-500">
            Hỗ trợ JPG, PNG. Kích thước &lt; 10MB. Tối đa 10 ảnh (khuyến nghị 5-7 ảnh).
          </span>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            multiple
            className="hidden"
            onChange={handleFileChange}
          />
        </label>
        
        {/* Image Previews */}
        {imagePreviews.length > 0 && (
          <div className="mt-4 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-slate-700">
                Đã chọn {imageFiles.length}/10 ảnh
              </span>
              {imageFiles.length < 10 && (
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="text-sm text-primary-600 hover:text-primary-700 font-medium"
                >
                  + Thêm ảnh
                </button>
              )}
            </div>
            <div className="space-y-3">
              {imagePreviews.map((preview, index) => (
                <div key={index} className="flex gap-3 rounded-xl border border-slate-200 bg-white p-3">
                  <div className="relative group flex-shrink-0">
                    <img
                      src={preview}
                      alt={`Preview ${index + 1}`}
                      className="h-24 w-24 rounded-lg object-cover shadow-inner"
                    />
                    <button
                      type="button"
                      onClick={() => handleRemoveImage(index)}
                      className="absolute top-1 right-1 rounded-full bg-rose-500 p-1.5 text-white opacity-0 transition-opacity group-hover:opacity-100 hover:bg-rose-600"
                      title="Xóa ảnh"
                    >
                      <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                    <div className="absolute bottom-1 left-1 rounded bg-black/50 px-1.5 py-0.5 text-xs text-white">
                      #{index + 1}
                    </div>
                  </div>
                  <div className="flex-1 min-w-0">
                    <label className="block text-xs font-semibold text-slate-600 mb-1">
                      Năm chụp ảnh (tùy chọn)
                    </label>
                    <input
                      type="number"
                      min="1900"
                      max={new Date().getFullYear()}
                      value={imageMetadataList[index]?.photo_year || ""}
                      onChange={(e) => handleImageMetadataChange(index, "photo_year", e.target.value)}
                      placeholder="VD: 2010"
                      className="w-full rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm text-slate-700 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-100"
                    />
                    <p className="mt-1 text-xs text-slate-400">
                      Giúp tính tuổi chính xác hơn khi matching
                    </p>
                  </div>
                </div>
              ))}
            </div>
            {imageFiles.length === 10 && (
              <p className="text-xs text-slate-500 text-center">
                Đã đạt giới hạn 10 ảnh. Xóa ảnh để thêm ảnh khác.
              </p>
            )}
          </div>
        )}
      </div>

      <div className="flex gap-3">
        <button
          type="button"
          onClick={handleReset}
          disabled={loading}
          className="flex-1 rounded-2xl border-2 border-slate-300 bg-white px-6 py-3 text-base font-semibold text-slate-700 transition hover:bg-slate-50 hover:border-slate-400 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Xóa hết
        </button>
        <button
          type="submit"
          disabled={loading}
          className="flex-1 rounded-2xl bg-gradient-to-r from-primary-600 to-blue-600 px-6 py-3 text-base font-semibold text-white shadow-lg shadow-primary-500/30 transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-70"
        >
          {loading ? "Đang xử lý..." : "Phân tích & tìm kiếm"}
        </button>
      </div>
    </form>

    {/* Confirmation Modal */}
    <ConfirmationModal
      isOpen={showConfirmModal}
      onClose={handleCancelConfirm}
      onConfirm={handleConfirmSubmit}
      data={metadata}
      mode={mode}
      imagePreview={imagePreviews[0]} // Show first image in modal
      imageCount={imageFiles.length}
    />
    </>
  );
}

UploadForm.propTypes = {
  mode: PropTypes.oneOf(["missing", "found"]).isRequired,
  onSubmit: PropTypes.func.isRequired,
  loading: PropTypes.bool
};

